New major
Financial-Times/o-visual-effects pull request #12
Opened 2017-05-25 13:27 UTC by onishiweb

Closes #11 
Closes #10 
Closes #9 
Closes #7

2017-05-25 13:30 UTC, i-like-robots commented
bye stripes!

2017-05-25 13:55 UTC, JakeChampion requested changes
Currently missing a migration guide

2017-05-25 14:46 UTC, JakeChampion approved these changes

2017-05-26 10:43 UTC, alicebartlett approved these changes

2017-05-26 10:59 UTC, merged